// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtV0co9K9eMzmpZD82a40QhwxyW0yDpKY',
    appId: '1:307151346923:web:a9c611da61f02c816c32ae',
    messagingSenderId: '307151346923',
    projectId: 'decor-8ccbd',
    authDomain: 'decor-8ccbd.firebaseapp.com',
    storageBucket: 'decor-8ccbd.firebasestorage.app',
    measurementId: 'G-39JM40PGBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqwFMBwV4nae5-KpUQeu9IU9w485vZBY',
    appId: '1:307151346923:android:fdbe272e999c205a6c32ae',
    messagingSenderId: '307151346923',
    projectId: 'decor-8ccbd',
    storageBucket: 'decor-8ccbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFaNyWMR84zVaHo1fOZ6qoyEu1BA7wppQ',
    appId: '1:307151346923:ios:59a8a56e26d743b46c32ae',
    messagingSenderId: '307151346923',
    projectId: 'decor-8ccbd',
    storageBucket: 'decor-8ccbd.firebasestorage.app',
    iosBundleId: 'com.example.decoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFaNyWMR84zVaHo1fOZ6qoyEu1BA7wppQ',
    appId: '1:307151346923:ios:59a8a56e26d743b46c32ae',
    messagingSenderId: '307151346923',
    projectId: 'decor-8ccbd',
    storageBucket: 'decor-8ccbd.firebasestorage.app',
    iosBundleId: 'com.example.decoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtV0co9K9eMzmpZD82a40QhwxyW0yDpKY',
    appId: '1:307151346923:web:25ce4ea21db42dec6c32ae',
    messagingSenderId: '307151346923',
    projectId: 'decor-8ccbd',
    authDomain: 'decor-8ccbd.firebaseapp.com',
    storageBucket: 'decor-8ccbd.firebasestorage.app',
    measurementId: 'G-DJ5B8PXJLY',
  );
}
