// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1BeLPjUdkGdUXeRFb6WIhV-QxY_orWk',
    appId: '1:237588759546:web:8847c7e80c023c02f41a43',
    messagingSenderId: '237588759546',
    projectId: 'decor-app-78f5b',
    authDomain: 'decor-app-78f5b.firebaseapp.com',
    storageBucket: 'decor-app-78f5b.firebasestorage.app',
    measurementId: 'G-DM6TKY6MM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZ-YZMkj2MoF2NTNa2UOJShd8hBIPDWM',
    appId: '1:237588759546:android:caecfc1dc2cd03b2f41a43',
    messagingSenderId: '237588759546',
    projectId: 'decor-app-78f5b',
    storageBucket: 'decor-app-78f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANt4yTxB1p9P_Ep0SGDSDxvgHYekKtBg8',
    appId: '1:237588759546:ios:c8496ed7445ffa99f41a43',
    messagingSenderId: '237588759546',
    projectId: 'decor-app-78f5b',
    storageBucket: 'decor-app-78f5b.firebasestorage.app',
    androidClientId: '237588759546-shjmfke1t33ldcei8ml6m03ic89v5u7t.apps.googleusercontent.com',
    iosClientId: '237588759546-5hkp83url9ot51rtdu6pisrtvbd3t3g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.decoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANt4yTxB1p9P_Ep0SGDSDxvgHYekKtBg8',
    appId: '1:237588759546:ios:c8496ed7445ffa99f41a43',
    messagingSenderId: '237588759546',
    projectId: 'decor-app-78f5b',
    storageBucket: 'decor-app-78f5b.firebasestorage.app',
    androidClientId: '237588759546-shjmfke1t33ldcei8ml6m03ic89v5u7t.apps.googleusercontent.com',
    iosClientId: '237588759546-5hkp83url9ot51rtdu6pisrtvbd3t3g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.decoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi1BeLPjUdkGdUXeRFb6WIhV-QxY_orWk',
    appId: '1:237588759546:web:78dfbc0ed9878a16f41a43',
    messagingSenderId: '237588759546',
    projectId: 'decor-app-78f5b',
    authDomain: 'decor-app-78f5b.firebaseapp.com',
    storageBucket: 'decor-app-78f5b.firebasestorage.app',
    measurementId: 'G-P3L2FXQGG3',
  );
}
